easy_admin:
    site_name: 'Laboratorios de Informática'

    formats:
            date:     'Y-m-d'
            time:     'H:i'
            datetime: 'Y-m-d H:i'

    list:
        max_results: 40
        actions:
            - { name: 'show', icon: 'eye', label: 'Ver' }
            - { name: 'edit', icon: 'edit', label: 'Editar' }
            - { name: 'delete', icon: 'remove', label: 'Borrar' }

    design:
        color_scheme: 'light'

#        form_theme: ['horizontal', ':form:fields.html.twig']

        menu:
            - label: 'Documentos'
              icon: 'file-text'
              children:
                - { entity: 'Documento', icon: 'file', label: 'Documentos' }
                - { entity: 'TipoDocumento', icon: 'tag', label: 'Tipos de Documento' }
#
#            - label: 'Prestamo Salas'
#              icon: 'calendar'
#              children:
#                - { entity: 'Evento', icon: 'calendar-o', label: 'Eventos' }
#                - { entity: 'SolicitudSala', icon: 'calendar-check-o', label: 'Solicitudes de Sala' }
#                - { entity: 'SolicitudSoftware', icon: 'windows', label: 'Solicitudes de Software' }
#                - { entity: 'PrestamoSemestral', icon: 'calendar-check-o', label: 'PrestamoSemestral' }

            - label: 'Inventario'
              icon: 'archive'
              children:
                - { entity: 'Elemento', icon: 'plug', label: 'Elementos' }
                - { entity: 'Equipo', icon: 'desktop', label: 'Equipos' }
                - { entity: 'Lugar', icon: 'map-marker', label: 'Lugares' }
#                - { entity: 'ObjetoEncontrado', icon: 'search', label: 'Objetos Encontrados' }
#                - { entity: 'Traslado', icon: 'truck', label: 'Traslados'}
#                - { label: 'Bajas' }
#                - { entity: 'Baja', icon: 'times-circle', label: 'Bajas'}
#                - { entity: 'MotivoBaja', icon: 'tag', label: 'Motivos de Baja' }
#
#            - label: 'Prestamos'
#              icon: 'shopping-bag'
#              children:
#                - { entity: 'PrestamoElemento', icon: 'microchip', label: 'Préstamo de Elementos' }
#                - { entity: 'PrestamoPracticaLibre', icon: 'desktop', label: 'Préstamo Práctica Libre', default: true }
#
#            - label: 'Soporte Salas'
#              icon: 'support'
#              children:
#                - { entity: 'Incidencia', icon: 'wrench', label: 'Incidencias' }
#                - { entity: 'SoporteFacultad', icon: 'ticket', label: 'Soportes Facultad' }
#                - { entity: 'MantenimientoExterno', icon: 'bug', label: 'Mantenimientos Externos' }

            - label: 'Universidad'
              icon: 'university'
              children:
                - { entity: 'Asignatura', icon: 'book', label: 'Asignaturas' }
                - { entity: 'Dependencia', icon: 'phone', label: 'Dependencias' }
                - { entity: 'Facultad', icon: 'building', label: 'Facultades' }
                - { entity: 'ProyectoCurricular', icon: 'graduation-cap', label: 'Proyectos Curriculares' }

            - { entity: 'Usuario', icon: 'users', label: 'Usuarios' }

#            - label: 'Reportes'
#              icon: 'files-o'
#              children:
#                - { label: 'Paz y Salvo', icon: 'check-circle', route: 'paz_salvo'}
#
#            - label: 'Graficos'
#              icon: 'line-chart'
#              children:
#                - { label: 'Práctica libre por mes', icon: 'bar-chart', route: 'practica_libre_mes'}
#
#            - { label: 'Editar Inicio', icon: 'pencil-square-o', route: 'editar_inicio'}

    entities:
        Usuario:
            class: App\Entity\Usuario
            controller: App\Controller\UsuarioController

            list:
                title: 'Usuarios'
                fields:
                    - { property: 'tipoDocumento' }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'activo'
                    - 'fechaCreacion'
                sort: 'fechaCreacion'

            show:
                fields:
                    - { property: 'tipoDocumento' }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'cargo'
                    - 'estado'
                    - 'dependencia'
                    - 'proyectoCurricular'
                    - 'activo'
                    - 'fechaCreacion'

            form:
                fields:
                    - { property: 'tipoDocumento', type: 'choice', label: 'Tipo de Documento', type_options: { choices:  { 'Cédula de Ciudadanía': 'C.C.' , 'Tarjeta de Identidad': 'T.I.', 'Cédula de Extranjería': 'C.E.' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - { property: 'passwordEnClaro', label: 'Contraseña', type: 'text' }
                    - { property: 'rol', type: 'choice', type_options: { choices:  { 'Estudiante': 'ROLE_ESTUDIANTE', 'Funcionario': 'ROLE_FUNCIONARIO', 'Docente': 'ROLE_DOCENTE', 'Administrador': 'ROLE_ADMIN' }, attr: { 'data-widget': 'select2' } } }
                    - 'cargo'
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Paz y Salvo': 'Paz y Salvo', 'En Mora': 'En Mora' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'dependencia', type: 'entity', type_options: { class: 'App\Entity\Dependencia', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguna' } }
                    - { property: 'proyectoCurricular', type: 'entity', type_options: { class: 'App\Entity\ProyectoCurricular', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguno' } }
                    - 'activo'

            new:
                fields:
                    - { property: 'email', type_options: { data: '@correo.udistrital.edu.co' } }

            edit:
                fields:
                    - { property: 'passwordEnClaro' }

        Dependencia:
            class: App\Entity\Dependencia

            list:
                title: 'Dependencias'
                sort: ['codigo', 'ASC']
                fields:
                    - 'codigo'
                    - 'nombre'
                    - 'facultad'

            edit:
                title: 'Modificar Dependencia'

            show:
                title: 'Dependencia'
                fields:
                    - 'codigo'
                    - 'nombre'
                    - 'facultad'

        ProyectoCurricular:
            class: App\Entity\ProyectoCurricular

            list:
                title: 'Proyectos Curriculares'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Proyecto Curricular' }
                fields:
                    - { property: 'id', type: 'text' }
                    - 'nombre'
                    - 'facultad'

            form:
                fields:
                    - { property: 'id', type: 'integer' }
                    - 'nombre'
                    - 'facultad'

            new:
                title: 'Crear Proyecto Curricular'

            edit:
                title: 'Modificar Proyecto Curricular'

            show:
                title: 'Proyecto Curricular'
                fields:
                    - 'id'
                    - 'nombre'
                    - 'facultad'

        Facultad:
            class: App\Entity\Facultad

            list:
                title: 'Facultades'

            show:
                fields:
                    - 'nombre'
                    - 'dependencias'
                    - 'proyectosCurriculares'

            form:
                fields:
                    - 'nombre'

        Lugar:
            class: App\Entity\Lugar
            controller: App\Controller\LugarController

            list:
                title: 'Lugares'

            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'cantidadEquipos'
                    - 'descripcion'
                    - 'visible'
                    
        Equipo:
            class: App\Entity\Equipo
            controller: App\Controller\EquipoController

            list:
                title: 'Equipos'
                sort: 'nombre'
                fields:
                    - { property: 'nombre' }
                    - { property: 'lugar' }
                    - { property: 'prestado', type: 'boolean' }
                    - { property: 'elementos' }

            show:
                fields:
                    - { property: 'nombre' }
                    - { property: 'lugar' }
                    - { property: 'prestado', type: 'boolean' }
                    - { property: 'elementos' }

            new:
                fields:
                    - { property: 'nombre' }
                    - { property: 'lugar', type: 'entity', type_options: { class: 'App\Entity\Lugar', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguno' } }
                    - { property: 'elementos' }

            edit:
                fields:
                    - { property: 'nombre', type: 'text', type_options: { disabled: true } }
                    - { property: 'lugar', type: 'entity', type_options: { class: 'App\Entity\Lugar', disabled: true, attr: { 'data-widget': 'select2' } } }
                    - { property: 'elementos' }

        Elemento:
            class: App\Entity\Elemento
            controller: App\Controller\ElementoController

            list:
                title: 'Elementos'
                fields:
                    - 'placa'
                    - 'serial'
                    - 'estado'
                    - 'tipo'
                    - 'tipoPrestamo'
                    - 'lugar'
                    - 'equipo'
                sort: 'lugar'

            show:
                fields:
                    - 'placa'
                    - 'modelo'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'tipo'
                    - 'lugar'
                    - 'equipo'
                    - { property: 'fechaIngreso', type: 'date' }
                    - 'estado'
                    - 'tipoPrestamo'
                    - { property: 'observaciones', type: 'raw' }
                    - 'prestado'
                    - 'activo'

            form:
                fields:
                    - 'placa'
                    - 'modelo'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - { property: 'lugar', type: 'entity', type_options: { class: 'App\Entity\Lugar', attr: { 'data-widget': 'select2' } } }
                    - { property: 'equipo', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Equipo' } }
                    - { property: 'fechaIngreso', type: 'date', type_options: { widget: 'single_text', html5: false } }
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Bueno': 'Bueno', 'Mantenimiento': 'Mantenimiento', Dañado': 'Dañado', 'Malo': 'Malo', 'Otro': 'Otro' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'tipo', type_options: { attr: { placeholder: 'CPU, Teclado, Monitor' } } }
                    - { property: 'tipoPrestamo', type: 'choice', type_options: { choices:  {  'Nadie': 'Nadie', 'Funcionarios': 'Funcionarios', 'Todos': 'Todos' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'observaciones', type: 'ckeditor' }
                    - { property: 'activo', type: 'checkbox' }

        Asignatura:
            class: App\Entity\Asignatura

            list:
                title: 'Asignaturas'
                sort: ['codigo', 'ASC']
                fields:
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'

            show:
                fields:
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'

        Documento:
            class: App\Entity\Documento
            controller: App\Controller\DocumentoController

            show:
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'usuarioSube', label: 'Subido por' }
                    - { property: 'archivo', template: 'archivo.html.twig', base_path: '%app.path.documentos%' }
                    - { property: 'fechaSubida', label: 'Fecha de subida' }

            list:
                title: 'Documentos'
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'usuarioSube', label: 'Subido por' }
                    - { property: 'archivo', template: 'archivo.html.twig', base_path: '%app.path.documentos%' }
                    - { property: 'fechaSubida', label: 'Fecha de subida' }
                sort: ['fechaSubida', 'DESC']

            form:
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'archivoFile', type: 'vich_file', label: 'Archivo' }

        TipoDocumento:
            class: App\Entity\TipoDocumento

            list:
                title: 'Tipos de Documento'
                sort: ['nombre', 'ASC']
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Tipo de Documento' }
                fields:
                    - 'nombre'
                    - 'documentos'

            show:
                title: 'Tipo de Documento (#%%entity_id%%)'
                fields:
                    - 'nombre'
                    - 'documentos'

            form:
                fields:
                    - 'nombre'

            new:
                title: 'Crear Tipo de Documento'

            edit:
                title: 'Modificar Tipo de Documento'

#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User