easy_admin:
    site_name: 'Laboratorios de Informática'

    formats:
            date:     'Y-m-d'
            time:     'H:i'
            datetime: 'Y-m-d H:i'

    list:
        max_results: 40
        actions:
            - { name: 'show', icon: 'eye', label: 'Ver' }
            - { name: 'edit', icon: 'edit', label: 'Editar' }
            - { name: 'delete', icon: 'remove', label: 'Borrar' }

    design:
        color_scheme: 'light'

#        form_theme: ['horizontal', ':form:fields.html.twig']

        menu:
#            - label: 'Documentos'
#              icon: 'file-text'
#              children:
#                - { entity: 'Documento', icon: 'file', label: 'Documentos' }
#                - { entity: 'TipoDocumento', icon: 'tag', label: 'Tipos de Documento' }
#
#            - label: 'Prestamo Salas'
#              icon: 'calendar'
#              children:
#                - { entity: 'Evento', icon: 'calendar-o', label: 'Eventos' }
#                - { entity: 'SolicitudSala', icon: 'calendar-check-o', label: 'Solicitudes de Sala' }
#                - { entity: 'SolicitudSoftware', icon: 'windows', label: 'Solicitudes de Software' }
#                - { entity: 'PrestamoSemestral', icon: 'calendar-check-o', label: 'PrestamoSemestral' }

#            - label: 'Inventario'
#              icon: 'archive'
#              children:
#                - { entity: 'Elemento', icon: 'plug', label: 'Elementos' }
#                - { entity: 'Equipo', icon: 'desktop', label: 'Equipos' }
#                - { entity: 'Lugar', icon: 'map-marker', label: 'Lugares' }
#                - { entity: 'ObjetoEncontrado', icon: 'search', label: 'Objetos Encontrados' }
#                - { entity: 'Traslado', icon: 'truck', label: 'Traslados'}
#                - { label: 'Bajas' }
#                - { entity: 'Baja', icon: 'times-circle', label: 'Bajas'}
#                - { entity: 'MotivoBaja', icon: 'tag', label: 'Motivos de Baja' }
#
#            - label: 'Prestamos'
#              icon: 'shopping-bag'
#              children:
#                - { entity: 'PrestamoElemento', icon: 'microchip', label: 'Préstamo de Elementos' }
#                - { entity: 'PrestamoPracticaLibre', icon: 'desktop', label: 'Préstamo Práctica Libre', default: true }
#
#            - label: 'Soporte Salas'
#              icon: 'support'
#              children:
#                - { entity: 'Incidencia', icon: 'wrench', label: 'Incidencias' }
#                - { entity: 'SoporteFacultad', icon: 'ticket', label: 'Soportes Facultad' }
#                - { entity: 'MantenimientoExterno', icon: 'bug', label: 'Mantenimientos Externos' }

            - label: 'Universidad'
              icon: 'university'
              children:
#                - { entity: 'Asignatura', icon: 'book', label: 'Asignaturas' }
                - { entity: 'Dependencia', icon: 'phone', label: 'Dependencias' }
                - { entity: 'Facultad', icon: 'building', label: 'Facultades' }
                - { entity: 'ProyectoCurricular', icon: 'graduation-cap', label: 'Proyectos Curriculares' }

            - { entity: 'Usuario', icon: 'users', label: 'Usuarios' }

#            - label: 'Reportes'
#              icon: 'files-o'
#              children:
#                - { label: 'Paz y Salvo', icon: 'check-circle', route: 'paz_salvo'}
#
#            - label: 'Graficos'
#              icon: 'line-chart'
#              children:
#                - { label: 'Práctica libre por mes', icon: 'bar-chart', route: 'practica_libre_mes'}
#
#            - { label: 'Editar Inicio', icon: 'pencil-square-o', route: 'editar_inicio'}

    entities:
        Usuario:
            class: App\Entity\Usuario
            controller: App\Controller\UsuarioController

            list:
                title: 'Usuarios'
                fields:
                    - { property: 'tipoDocumento' }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'activo'
                    - 'fechaCreacion'
                sort: 'fechaCreacion'

            show:
                fields:
                    - { property: 'tipoDocumento' }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'cargo'
                    - 'estado'
                    - 'dependencia'
                    - 'proyectoCurricular'
                    - 'activo'
                    - 'fechaCreacion'

            form:
                fields:
                    - { property: 'tipoDocumento', type: 'choice', label: 'Tipo de Documento', type_options: { choices:  { 'Cédula de Ciudadanía': 'C.C.' , 'Tarjeta de Identidad': 'T.I.', 'Cédula de Extranjería': 'C.E.' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - { property: 'passwordEnClaro', label: 'Contraseña', type: 'text' }
                    - { property: 'rol', type: 'choice', type_options: { choices:  { 'Estudiante': 'ROLE_ESTUDIANTE', 'Funcionario': 'ROLE_FUNCIONARIO', 'Docente': 'ROLE_DOCENTE', 'Administrador': 'ROLE_ADMIN' }, attr: { 'data-widget': 'select2' } } }
                    - 'cargo'
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Paz y Salvo': 'Paz y Salvo', 'En Mora': 'En Mora' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'dependencia', type: 'entity', type_options: { class: 'App\Entity\Dependencia', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguna' } }
                    - { property: 'proyectoCurricular', type: 'entity', type_options: { class: 'App\Entity\ProyectoCurricular', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguno' } }
                    - 'activo'

            new:
                fields:
                    - { property: 'email', type_options: { data: '@correo.udistrital.edu.co' } }

            edit:
                fields:
                    - { property: 'passwordEnClaro' }

        Dependencia:
            class: App\Entity\Dependencia

            list:
                title: 'Dependencias'
                sort: ['codigo', 'ASC']
                fields:
                    - 'codigo'
                    - 'nombre'
                    - 'facultad'

            edit:
                title: 'Modificar Dependencia'

            show:
                title: 'Dependencia'
                fields:
                    - 'codigo'
                    - 'nombre'
                    - 'facultad'

        ProyectoCurricular:
            class: App\Entity\ProyectoCurricular

            list:
                title: 'Proyectos Curriculares'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Proyecto Curricular' }
                fields:
                    - { property: 'id', type: 'text' }
                    - 'nombre'
                    - 'facultad'

            form:
                fields:
                    - { property: 'id', type: 'integer' }
                    - 'nombre'
                    - 'facultad'

            new:
                title: 'Crear Proyecto Curricular'

            edit:
                title: 'Modificar Proyecto Curricular'

            show:
                title: 'Proyecto Curricular'
                fields:
                    - 'id'
                    - 'nombre'
                    - 'facultad'

        Facultad:
            class: App\Entity\Facultad

            list:
                title: 'Facultades'

            show:
                fields:
                    - 'nombre'
                    - 'dependencias'
                    - 'proyectosCurriculares'

            form:
                fields:
                    - 'nombre'

#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
