vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        documentos:
            uri_prefix: '%app.path.documentos%'
            upload_destination: '%kernel.root_dir%/../web/%app.path.documentos%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
